import type { NamedTiming } from './types.ts'

/**
 * VESA DMT — Display Monitor Timings, 1.0 rev 13.
 *
 * CURATED, NOT EXHAUSTIVE. DMT has ~90 entries and most are legacy CRT modes
 * nobody will put through an event processor. What is here is every mode this
 * fleet's kit actually meets, each one carrying its published values rather
 * than a re-derivation — a mode generated by our own CVT code and then labelled
 * "DMT" would be circular, and the tests use these entries to check the CVT
 * implementation, which only works if they are independent of it.
 *
 * `code` is the DMT ID, which is what a Standard Timing descriptor and a CVT
 * 3-byte code both reference.
 */

interface Row {
  code: number
  name: string
  h: number
  hf: number
  hs: number
  hb: number
  v: number
  vf: number
  vs: number
  vb: number
  /** Pixel clock in kHz — DMT quotes 25.175 and 74.25, which are not integers
   *  in MHz, and floating point at MHz scale loses them. */
  clk: number
  hp: boolean
  vp: boolean
  rb?: boolean
}

const ROWS: Row[] = [
  { code: 0x04, name: '640x480 @60', h: 640, hf: 16, hs: 96, hb: 48, v: 480, vf: 10, vs: 2, vb: 33, clk: 25175, hp: false, vp: false },
  { code: 0x09, name: '800x600 @60', h: 800, hf: 40, hs: 128, hb: 88, v: 600, vf: 1, vs: 4, vb: 23, clk: 40000, hp: true, vp: true },
  { code: 0x0a, name: '800x600 @72', h: 800, hf: 56, hs: 120, hb: 64, v: 600, vf: 37, vs: 6, vb: 23, clk: 50000, hp: true, vp: true },
  { code: 0x0b, name: '800x600 @75', h: 800, hf: 16, hs: 80, hb: 160, v: 600, vf: 1, vs: 3, vb: 21, clk: 49500, hp: true, vp: true },
  { code: 0x10, name: '1024x768 @60', h: 1024, hf: 24, hs: 136, hb: 160, v: 768, vf: 3, vs: 6, vb: 29, clk: 65000, hp: false, vp: false },
  { code: 0x12, name: '1024x768 @75', h: 1024, hf: 16, hs: 96, hb: 176, v: 768, vf: 1, vs: 3, vb: 28, clk: 78750, hp: true, vp: true },
  { code: 0x17, name: '1152x864 @75', h: 1152, hf: 64, hs: 128, hb: 256, v: 864, vf: 1, vs: 3, vb: 32, clk: 108000, hp: true, vp: true },
  { code: 0x1b, name: '1280x800 @60 RB', h: 1280, hf: 48, hs: 32, hb: 80, v: 800, vf: 3, vs: 6, vb: 14, clk: 71000, hp: true, vp: false, rb: true },
  { code: 0x1c, name: '1280x800 @60', h: 1280, hf: 72, hs: 128, hb: 200, v: 800, vf: 3, vs: 6, vb: 22, clk: 83500, hp: false, vp: true },
  { code: 0x20, name: '1280x960 @60', h: 1280, hf: 96, hs: 112, hb: 312, v: 960, vf: 1, vs: 3, vb: 36, clk: 108000, hp: true, vp: true },
  { code: 0x23, name: '1280x1024 @60', h: 1280, hf: 48, hs: 112, hb: 248, v: 1024, vf: 1, vs: 3, vb: 38, clk: 108000, hp: true, vp: true },
  { code: 0x24, name: '1280x1024 @75', h: 1280, hf: 16, hs: 144, hb: 248, v: 1024, vf: 1, vs: 3, vb: 38, clk: 135000, hp: true, vp: true },
  { code: 0x27, name: '1360x768 @60', h: 1360, hf: 64, hs: 112, hb: 256, v: 768, vf: 3, vs: 6, vb: 18, clk: 85500, hp: true, vp: true },
  { code: 0x29, name: '1400x1050 @60', h: 1400, hf: 88, hs: 144, hb: 232, v: 1050, vf: 3, vs: 4, vb: 32, clk: 121750, hp: false, vp: true },
  { code: 0x2e, name: '1440x900 @60 RB', h: 1440, hf: 48, hs: 32, hb: 80, v: 900, vf: 3, vs: 6, vb: 17, clk: 88750, hp: true, vp: false, rb: true },
  { code: 0x2f, name: '1440x900 @60', h: 1440, hf: 80, hs: 152, hb: 232, v: 900, vf: 3, vs: 6, vb: 25, clk: 106500, hp: false, vp: true },
  { code: 0x33, name: '1600x1200 @60', h: 1600, hf: 64, hs: 192, hb: 304, v: 1200, vf: 1, vs: 3, vb: 46, clk: 162000, hp: true, vp: true },
  { code: 0x39, name: '1680x1050 @60 RB', h: 1680, hf: 48, hs: 32, hb: 80, v: 1050, vf: 3, vs: 6, vb: 21, clk: 119000, hp: true, vp: false, rb: true },
  { code: 0x3a, name: '1680x1050 @60', h: 1680, hf: 104, hs: 176, hb: 280, v: 1050, vf: 3, vs: 6, vb: 30, clk: 146250, hp: false, vp: true },
  { code: 0x41, name: '1920x1080 @60', h: 1920, hf: 88, hs: 44, hb: 148, v: 1080, vf: 4, vs: 5, vb: 36, clk: 148500, hp: true, vp: true },
  { code: 0x44, name: '1920x1200 @60 RB', h: 1920, hf: 48, hs: 32, hb: 80, v: 1200, vf: 3, vs: 6, vb: 26, clk: 154000, hp: true, vp: false, rb: true },
  { code: 0x45, name: '1920x1200 @60', h: 1920, hf: 136, hs: 200, hb: 336, v: 1200, vf: 3, vs: 6, vb: 36, clk: 193250, hp: false, vp: true },
  { code: 0x49, name: '2560x1600 @60 RB', h: 2560, hf: 48, hs: 32, hb: 80, v: 1600, vf: 3, vs: 6, vb: 37, clk: 268500, hp: true, vp: false, rb: true },
  { code: 0x4a, name: '2560x1600 @60', h: 2560, hf: 192, hs: 280, hb: 472, v: 1600, vf: 3, vs: 6, vb: 49, clk: 348500, hp: false, vp: true },
  { code: 0x51, name: '1366x768 @60', h: 1366, hf: 70, hs: 143, hb: 213, v: 768, vf: 3, vs: 3, vb: 24, clk: 85500, hp: true, vp: true },
  { code: 0x52, name: '1920x1080 @60 (CTA)', h: 1920, hf: 88, hs: 44, hb: 148, v: 1080, vf: 4, vs: 5, vb: 36, clk: 148500, hp: true, vp: true },
  { code: 0x54, name: '2048x1152 @60 RB', h: 2048, hf: 26, hs: 80, hb: 96, v: 1152, vf: 3, vs: 5, vb: 40, clk: 162000, hp: true, vp: false, rb: true },
  { code: 0x55, name: '1280x720 @60', h: 1280, hf: 110, hs: 40, hb: 220, v: 720, vf: 5, vs: 5, vb: 20, clk: 74250, hp: true, vp: true },
  { code: 0x56, name: '1366x768 @60 RB', h: 1366, hf: 14, hs: 56, hb: 64, v: 768, vf: 1, vs: 3, vb: 28, clk: 72000, hp: true, vp: false, rb: true },
]

export const DMT_TIMINGS: NamedTiming[] = ROWS.map((r) => ({
  name: `${r.name}`,
  standard: 'dmt',
  code: r.code,
  hActive: r.h,
  hFront: r.hf,
  hSync: r.hs,
  hBack: r.hb,
  vActive: r.v,
  vFront: r.vf,
  vSync: r.vs,
  vBack: r.vb,
  pixelClockHz: r.clk * 1000,
  interlaced: false,
  hSyncPositive: r.hp,
  vSyncPositive: r.vp,
}))

export function dmtByCode(code: number): NamedTiming | undefined {
  return DMT_TIMINGS.find((t) => t.code === code)
}
