import { describe, expect, it } from 'vitest'
import fx from './fixtures/reference-tiles.json'
import { buildMosaic, checkMosaic, DEFAULT_MOSAIC, mosaicErrors, tileLabel } from '../mosaic.ts'
import type { MosaicRequest } from '../mosaic.ts'
import { decodeEdid } from '../edid/decode.ts'
import { encodeDisplayId, encodeTiledTopology, decodeTiledTopology } from '../edid/displayid.ts'
import { primaryTiming } from '../primary.ts'
import { vFreq } from '../timing/types.ts'
import type { DisplayIdExtension, TiledTopology } from '../edid/types.ts'

const hex = (b: Uint8Array) => [...b].map((x) => x.toString(16).padStart(2, '0')).join('')
const bytes = (h: string) => Uint8Array.from(h.match(/../g)!.map((x) => parseInt(x, 16)))

/**
 * The fixtures are the reference tiled-EDID builder's own output, generated by
 * running it under node — the builder whose files have bonded on real Macs. Matching it byte for byte is
 * the whole claim this mode makes, so any drift has to fail here.
 */
describe('matches the reference builder byte for byte', () => {
  for (const c of fx.cases) {
    const inp = c.input as { width: number; height: number; cols: number; rows: number; hz: number; prefix: string; bitDepth: number; group?: number[] }
    it(`${inp.width}x${inp.height} @${inp.hz} as ${inp.cols}x${inp.rows}`, () => {
      const req: MosaicRequest = {
        ...DEFAULT_MOSAIC,
        width: inp.width,
        height: inp.height,
        cols: inp.cols,
        rows: inp.rows,
        refreshHz: inp.hz,
        bitDepth: inp.bitDepth as 8 | 10,
        group: inp.group ? inp.group[1] : 1,
      }
      // The reference names every tile after the prefix, or after its side when
      // there is none.
      const r = buildMosaic(req, (col, row) => inp.prefix || tileLabel(inp.cols, inp.rows, col, row))
      expect(r.tiles.map((t) => t.file)).toEqual(c.tiles.map((t) => t.file))
      r.tiles.forEach((t, i) => expect(hex(t.bytes)).toBe(c.tiles[i].hex))
    })
  }
})

describe('tiled topology block', () => {
  const sample: TiledTopology = {
    capabilities: 0x8a,
    hTiles: 20,
    vTiles: 3,
    hLocation: 17,
    vLocation: 2,
    tileWidth: 3840,
    tileHeight: 2160,
    bezel: [1, 2, 3, 4, 5],
    topologyId: [0x4f, 0x54, 0x52, 0x12, 0x34, 1, 2, 3, 4],
  }

  it('is 22 bytes and round-trips', () => {
    const b = encodeTiledTopology(sample)
    expect(b.length).toBe(22)
    expect(decodeTiledTopology(b)).toEqual(sample)
  })

  it('agrees with the kernel parser, drm_parse_tiled_block', () => {
    // The formulas below are copied from drm_edid.c, not derived from ours.
    const t = encodeTiledTopology(sample)
    const topo = [t[1], t[2], t[3]]
    const num_v_tile = (topo[0] & 0xf) | (topo[2] & 0x30)
    const num_h_tile = (topo[0] >> 4) | ((topo[2] >> 2) & 0x30)
    const tile_v_loc = (topo[1] & 0xf) | ((topo[2] & 0x3) << 4)
    const tile_h_loc = (topo[1] >> 4) | (((topo[2] >> 2) & 0x3) << 4)
    expect(num_h_tile + 1).toBe(20)
    expect(num_v_tile + 1).toBe(3)
    expect(tile_h_loc).toBe(17)
    expect(tile_v_loc).toBe(2)
    expect((t[4] | (t[5] << 8)) + 1).toBe(3840)
    expect((t[6] | (t[7] << 8)) + 1).toBe(2160)
    expect(!!(t[0] & 0x80)).toBe(true)
  })

  it('refuses a location outside the grid', () => {
    expect(() => encodeTiledTopology({ ...sample, hLocation: 20 })).toThrow(/outside/)
  })

  it('uses tag 0x28 in a DisplayID 2.0 section and 0x12 in 1.3', () => {
    const ext = (version: number): DisplayIdExtension => ({
      kind: 'displayid', version, primaryUseCase: 0, extensionCount: 0, type7Timings: [], unknownBlocks: [], tiled: sample,
    })
    expect(encodeDisplayId(ext(0x20))[5]).toBe(0x28)
    expect(encodeDisplayId(ext(0x12))[5]).toBe(0x12)
  })
})

describe('a built tile, read back', () => {
  const r = buildMosaic({ ...DEFAULT_MOSAIC, width: 7680, height: 2160, refreshHz: 50 })

  it('decodes to its own place in the grid, one topology id across the set', () => {
    const tiles = r.tiles.map((t) => {
      const d = decodeEdid(t.bytes)
      expect(d.issues.filter((i) => i.severity === 'error')).toEqual([])
      return (d.edid.extensions.find((e) => e.kind === 'displayid') as DisplayIdExtension).tiled!
    })
    expect(tiles.map((t) => [t.hLocation, t.vLocation])).toEqual([[0, 0], [1, 0]])
    expect(tiles.every((t) => t.hTiles === 2 && t.vTiles === 1 && t.tileWidth === 3840 && t.tileHeight === 2160)).toBe(true)
    expect(new Set(tiles.map((t) => hex(Uint8Array.from(t.topologyId)))).size).toBe(1)
  })

  it('makes the Type I tile mode the primary timing', () => {
    const t = primaryTiming(decodeEdid(r.tiles[0].bytes).edid)!
    expect(t.hActive).toBe(3840)
    expect(t.vActive).toBe(2160)
    expect(vFreq(t)).toBeCloseTo(50, 1)
  })

  it('keeps its DisplayID bytes through a decode/encode — padding included', () => {
    const did = decodeEdid(r.tiles[0].bytes).edid.extensions[1] as DisplayIdExtension
    expect(did.sectionLength).toBe(121)
    expect(hex(Uint8Array.from(encodeDisplayId(did)))).toBe(hex(r.tiles[0].bytes.slice(256)))
  })

  it('reads a reference file the same way', () => {
    const d = decodeEdid(bytes(fx.cases[3].tiles[3].hex)).edid
    const t = (d.extensions[1] as DisplayIdExtension).tiled!
    expect([t.hTiles, t.vTiles, t.hLocation, t.vLocation]).toEqual([2, 2, 1, 1])
  })
})

describe('what a Mac will make of it', () => {
  const level = (req: Partial<MosaicRequest>, what: RegExp) =>
    checkMosaic({ ...DEFAULT_MOSAIC, ...req }).find((c) => what.test(c.what))?.level

  it('bands the width: any macOS, macOS 27, untested', () => {
    expect(level({ width: 6144 }, /wide/)).toBe('ok')
    expect(level({ width: 7680 }, /wide/)).toBe('warn')
    expect(level({ width: 12288 }, /wide/)).toBe('warn')
    expect(level({ width: 12800 }, /wide/)).toBe('bad')
  })

  it('only 2 x 1 and 2 x 2 bond', () => {
    expect(level({ cols: 2, rows: 1 }, /bond/)).toBe('ok')
    expect(level({ cols: 2, rows: 2 }, /bond/)).toBe('warn')
    expect(level({ cols: 3, rows: 1 }, /bond/)).toBe('bad')
    expect(level({ cols: 1, rows: 2 }, /bond/)).toBe('bad')
  })

  it('refuses a tile wider than 6144, an odd split, a bad vendor id', () => {
    expect(mosaicErrors({ ...DEFAULT_MOSAIC, width: 12800 })).toContainEqual(expect.stringMatching(/6400 wide/))
    expect(mosaicErrors({ ...DEFAULT_MOSAIC, width: 6152, cols: 2 })).toEqual([])
    expect(mosaicErrors({ ...DEFAULT_MOSAIC, height: 2161, rows: 2 })).toContainEqual(expect.stringMatching(/2161/))
    expect(mosaicErrors({ ...DEFAULT_MOSAIC, vendor: 'at' })).toContainEqual(expect.stringMatching(/vendor/))
  })
})

describe('zip of the set', () => {
  it('writes a stored archive every unzip can read', async () => {
    const { zipStored, crc32 } = await import('../zip.ts')
    // The standard CRC-32 check value.
    expect(crc32(new TextEncoder().encode('123456789'))).toBe(0xcbf43926)
    const r = buildMosaic(DEFAULT_MOSAIC)
    const z = zipStored(r.tiles.map((t) => ({ name: t.file, data: t.bytes })))
    const { execFileSync } = await import('node:child_process')
    const { mkdtempSync, writeFileSync, readFileSync } = await import('node:fs')
    const { join } = await import('node:path')
    const { tmpdir } = await import('node:os')
    const dir = mkdtempSync(join(tmpdir(), 'otter-zip-'))
    writeFileSync(join(dir, 'set.zip'), z)
    execFileSync('unzip', ['-q', join(dir, 'set.zip'), '-d', join(dir, 'out')])
    for (const t of r.tiles) expect(hex(new Uint8Array(readFileSync(join(dir, 'out', t.file))))).toBe(hex(t.bytes))
  })
})
